import { PersonsMap, Sex } from "../../types/Types";

export const sampleTree: PersonsMap = {
  "1": {
    parent_of_family_id: [],
    child_of_family_id: [1],
    person_data: {
      person_id: 1,
      name: "Steven Ryan /Gray/",
      birthday: "1979-03-22",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "2": {
    parent_of_family_id: [1],
    child_of_family_id: [2, 4],
    person_data: {
      person_id: 2,
      name: "Steven Dean /Gray/",
      birthday: "1953-09-02",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "3": {
    parent_of_family_id: [1],
    child_of_family_id: [15],
    person_data: {
      person_id: 3,
      name: "Janice /Roberts/",
      birthday: null,
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "4": {
    parent_of_family_id: [2],
    child_of_family_id: [3],
    person_data: {
      person_id: 4,
      name: "Dean Williams /Gray/",
      birthday: "1926-08-03",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "5": {
    parent_of_family_id: [2, 4, 7],
    child_of_family_id: [9],
    person_data: {
      person_id: 5,
      name: "Mary Carol /Brockbank/",
      birthday: "1926-12-23",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "6": {
    parent_of_family_id: [4],
    child_of_family_id: [3],
    person_data: {
      person_id: 6,
      name: "Dean William /Gray/",
      birthday: null,
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "7": {
    parent_of_family_id: [15],
    child_of_family_id: [16],
    person_data: {
      person_id: 7,
      name: "John Oral /Roberts/",
      birthday: null,
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "8": {
    parent_of_family_id: [15],
    child_of_family_id: [19],
    person_data: {
      person_id: 8,
      name: "Elaine /Steed/",
      birthday: "1926-12-09",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "9": {
    parent_of_family_id: [3],
    child_of_family_id: [5],
    person_data: {
      person_id: 9,
      name: "Seymour Dean /Gray/",
      birthday: "1894-10-01",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "10": {
    parent_of_family_id: [3],
    child_of_family_id: [6],
    person_data: {
      person_id: 10,
      name: "Vera Eliza /Williams/",
      birthday: "1903-08-15",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "11": {
    parent_of_family_id: [8, 9],
    child_of_family_id: [10],
    person_data: {
      person_id: 11,
      name: "Issac Elmer /Brockbank/",
      birthday: "1882-10-17",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "12": {
    parent_of_family_id: [9],
    child_of_family_id: [13],
    person_data: {
      person_id: 12,
      name: "Elsie Vernessa Booth /Brockbank/",
      birthday: "1894-04-12",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "13": {
    parent_of_family_id: [7],
    child_of_family_id: [],
    person_data: {
      person_id: 13,
      name: 'Ivan Allred "Ike" /Olson/',
      birthday: "1926-07-26",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "14": {
    parent_of_family_id: [5],
    child_of_family_id: [],
    person_data: {
      person_id: 14,
      name: "William Henry /Gray/",
      birthday: "1837-11-01",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "15": {
    parent_of_family_id: [5],
    child_of_family_id: [],
    person_data: {
      person_id: 15,
      name: "Eleanor Miller /Strong/",
      birthday: "1847-01-30",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "16": {
    parent_of_family_id: [],
    child_of_family_id: [3],
    person_data: {
      person_id: 16,
      name: "Bessie Louise /Gray/",
      birthday: "1924-05-22",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "17": {
    parent_of_family_id: [],
    child_of_family_id: [3],
    person_data: {
      person_id: 17,
      name: "Carolyn /Poulson/",
      birthday: "1931-12-23",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "18": {
    parent_of_family_id: [6],
    child_of_family_id: [],
    person_data: {
      person_id: 18,
      name: "Don Carlos /Williams/",
      birthday: "1874-05-24",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "19": {
    parent_of_family_id: [6],
    child_of_family_id: [],
    person_data: {
      person_id: 19,
      name: "Caroline Melissa /Bunnell/",
      birthday: "1876-08-14",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "20": {
    parent_of_family_id: [],
    child_of_family_id: [5],
    person_data: {
      person_id: 20,
      name: "Sterling Robert /Gray/",
      birthday: "1876-04-08",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "21": {
    parent_of_family_id: [],
    child_of_family_id: [5],
    person_data: {
      person_id: 21,
      name: "Estella Alice /Gray/",
      birthday: "1878-09-22",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "22": {
    parent_of_family_id: [],
    child_of_family_id: [5],
    person_data: {
      person_id: 22,
      name: "William Leonard /Gray/",
      birthday: "1870-03-01",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "23": {
    parent_of_family_id: [],
    child_of_family_id: [5],
    person_data: {
      person_id: 23,
      name: "Morris H /Gray/",
      birthday: "1886-01-16",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "24": {
    parent_of_family_id: [],
    child_of_family_id: [5],
    person_data: {
      person_id: 24,
      name: "Julia Ann /Gray/",
      birthday: "1872-10-09",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "25": {
    parent_of_family_id: [],
    child_of_family_id: [5],
    person_data: {
      person_id: 25,
      name: "Spencer Strong /Gray/",
      birthday: "1881-07-16",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "26": {
    parent_of_family_id: [],
    child_of_family_id: [5],
    person_data: {
      person_id: 26,
      name: "Wilford /Grey/",
      birthday: "1889-02-18",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "27": {
    parent_of_family_id: [],
    child_of_family_id: [5],
    person_data: {
      person_id: 27,
      name: "Sarah Ellen /Gray/",
      birthday: "1869-02-09",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "28": {
    parent_of_family_id: [],
    child_of_family_id: [6],
    person_data: {
      person_id: 28,
      name: "Bessie Williams /Whitehead/",
      birthday: "1906-01-13",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "29": {
    parent_of_family_id: [],
    child_of_family_id: [6],
    person_data: {
      person_id: 29,
      name: "Leola /Williams/",
      birthday: "1909-07-11",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "30": {
    parent_of_family_id: [],
    child_of_family_id: [6],
    person_data: {
      person_id: 30,
      name: "Merle /Williams/",
      birthday: "1911-08-04",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "31": {
    parent_of_family_id: [],
    child_of_family_id: [6],
    person_data: {
      person_id: 31,
      name: "Max Donald /Williams/",
      birthday: "1914-05-07",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "32": {
    parent_of_family_id: [],
    child_of_family_id: [6],
    person_data: {
      person_id: 32,
      name: "/Williams/",
      birthday: "1897-09-23",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "33": {
    parent_of_family_id: [],
    child_of_family_id: [6],
    person_data: {
      person_id: 33,
      name: "Lloyd Bunnell /Williams/",
      birthday: "1899-04-24",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "34": {
    parent_of_family_id: [],
    child_of_family_id: [6],
    person_data: {
      person_id: 34,
      name: "Earl Lynn /Williams/",
      birthday: "1917-02-01",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "35": {
    parent_of_family_id: [10],
    child_of_family_id: [],
    person_data: {
      person_id: 35,
      name: "Joshua /Brockbank/",
      birthday: "1848-05-15",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "36": {
    parent_of_family_id: [10],
    child_of_family_id: [],
    person_data: {
      person_id: 36,
      name: "Sarah Ann Traxon /Jex/",
      birthday: "1851-04-01",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "37": {
    parent_of_family_id: [8],
    child_of_family_id: [],
    person_data: {
      person_id: 37,
      name: "Zoe May /Brimhall/",
      birthday: "1883-09-29",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "38": {
    parent_of_family_id: [],
    child_of_family_id: [8],
    person_data: {
      person_id: 38,
      name: "Alma /Brockbank/",
      birthday: "1909-09-18",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "39": {
    parent_of_family_id: [],
    child_of_family_id: [8],
    person_data: {
      person_id: 39,
      name: "Ila Brimhall /Brockbank/",
      birthday: "1911-08-02",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "40": {
    parent_of_family_id: [],
    child_of_family_id: [9],
    person_data: {
      person_id: 40,
      name: "Shirley /Brockbank/",
      birthday: "1919-12-10",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "41": {
    parent_of_family_id: [],
    child_of_family_id: [9],
    person_data: {
      person_id: 41,
      name: "Barbara Kay /Brockbank/",
      birthday: "1936-06-01",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "42": {
    parent_of_family_id: [],
    child_of_family_id: [9],
    person_data: {
      person_id: 42,
      name: "Leah Patricia /Fillmore/",
      birthday: "1924-10-16",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "43": {
    parent_of_family_id: [],
    child_of_family_id: [9],
    person_data: {
      person_id: 43,
      name: "Stillborn Baby Girl /Brockbank/",
      birthday: "1931-11-30",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "44": {
    parent_of_family_id: [],
    child_of_family_id: [9],
    person_data: {
      person_id: 44,
      name: "Elinor Brockbank /Brimhall/",
      birthday: "1922-03-01",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "45": {
    parent_of_family_id: [],
    child_of_family_id: [9],
    person_data: {
      person_id: 45,
      name: "Helen Brockbank /Weech/",
      birthday: "1917-11-24",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "46": {
    parent_of_family_id: [11, 12, 13, 14],
    child_of_family_id: [],
    person_data: {
      person_id: 46,
      name: "John Edge /Booth/",
      birthday: "1847-06-29",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "47": {
    parent_of_family_id: [13],
    child_of_family_id: [],
    person_data: {
      person_id: 47,
      name: "Delia Ina /Winders/",
      birthday: "1854-03-16",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "48": {
    parent_of_family_id: [],
    child_of_family_id: [10],
    person_data: {
      person_id: 48,
      name: "Delbert Daniel /Brockbank/",
      birthday: "1880-04-08",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "49": {
    parent_of_family_id: [],
    child_of_family_id: [10],
    person_data: {
      person_id: 49,
      name: "Elener Rebecca /Brockbank/",
      birthday: "1894-07-10",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "50": {
    parent_of_family_id: [],
    child_of_family_id: [10],
    person_data: {
      person_id: 50,
      name: "Merrill J /Brockbank/",
      birthday: "1896-09-29",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "51": {
    parent_of_family_id: [],
    child_of_family_id: [10],
    person_data: {
      person_id: 51,
      name: "Heber David /Brockbank/",
      birthday: "1891-12-27",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "52": {
    parent_of_family_id: [],
    child_of_family_id: [10],
    person_data: {
      person_id: 52,
      name: "Lillian Christena /Brockbank/",
      birthday: "1877-11-10",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "53": {
    parent_of_family_id: [],
    child_of_family_id: [10],
    person_data: {
      person_id: 53,
      name: "Albert Goodson /Brockbank/",
      birthday: "1884-09-07",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "54": {
    parent_of_family_id: [],
    child_of_family_id: [10],
    person_data: {
      person_id: 54,
      name: "Elizabeth Vilate /Brockbank/",
      birthday: "1873-06-26",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "55": {
    parent_of_family_id: [],
    child_of_family_id: [10],
    person_data: {
      person_id: 55,
      name: "Sarah Ann /Brockbank/",
      birthday: "1870-01-04",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "56": {
    parent_of_family_id: [],
    child_of_family_id: [10],
    person_data: {
      person_id: 56,
      name: "Joshua Richard /Brockbank/",
      birthday: "1872-01-21",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "57": {
    parent_of_family_id: [],
    child_of_family_id: [10],
    person_data: {
      person_id: 57,
      name: "Henry Archibald /Brockbank/",
      birthday: "1889-11-29",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "58": {
    parent_of_family_id: [],
    child_of_family_id: [10],
    person_data: {
      person_id: 58,
      name: "William Ernest /Brockbank/",
      birthday: "1875-09-19",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "59": {
    parent_of_family_id: [],
    child_of_family_id: [10],
    person_data: {
      person_id: 59,
      name: "Willis Mainwaring /Brockbank/",
      birthday: "1886-11-28",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "60": {
    parent_of_family_id: [11],
    child_of_family_id: [],
    person_data: {
      person_id: 60,
      name: "Maria Josephine /Harvey/",
      birthday: "1850-01-31",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "61": {
    parent_of_family_id: [12],
    child_of_family_id: [],
    person_data: {
      person_id: 61,
      name: "Hannah /Billings/",
      birthday: "1852-03-12",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "62": {
    parent_of_family_id: [14],
    child_of_family_id: [],
    person_data: {
      person_id: 62,
      name: "Ann Eliz'th Henrietta /Twelves/",
      birthday: "1848-07-26",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "63": {
    parent_of_family_id: [],
    child_of_family_id: [11],
    person_data: {
      person_id: 63,
      name: "Vienna Hortense /Booth/",
      birthday: "1878-04-14",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "64": {
    parent_of_family_id: [],
    child_of_family_id: [11],
    person_data: {
      person_id: 64,
      name: "Hannah Rowena /Booth/",
      birthday: "1882-04-13",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "65": {
    parent_of_family_id: [],
    child_of_family_id: [11],
    person_data: {
      person_id: 65,
      name: "John Edge /Booth/",
      birthday: "1874-07-20",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "66": {
    parent_of_family_id: [],
    child_of_family_id: [11],
    person_data: {
      person_id: 66,
      name: "Josephine Diantha /Booth/",
      birthday: "1876-03-16",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "67": {
    parent_of_family_id: [],
    child_of_family_id: [11],
    person_data: {
      person_id: 67,
      name: "Richard Harvey /Booth/",
      birthday: "1884-05-06",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "68": {
    parent_of_family_id: [],
    child_of_family_id: [13],
    person_data: {
      person_id: 68,
      name: "Edwin Winters /Booth/",
      birthday: "1896-06-11",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "69": {
    parent_of_family_id: [],
    child_of_family_id: [13],
    person_data: {
      person_id: 69,
      name: "James Milton /Booth/",
      birthday: "1888-05-21",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "70": {
    parent_of_family_id: [],
    child_of_family_id: [13],
    person_data: {
      person_id: 70,
      name: "Maria Delilah /Booth/",
      birthday: "1890-01-07",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "71": {
    parent_of_family_id: [16],
    child_of_family_id: [17],
    person_data: {
      person_id: 71,
      name: "Millard J /Roberts/",
      birthday: "1890-11-29",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "72": {
    parent_of_family_id: [16],
    child_of_family_id: [18],
    person_data: {
      person_id: 72,
      name: "Martha Ann /Helquist/",
      birthday: "1893-09-24",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "73": {
    parent_of_family_id: [19],
    child_of_family_id: [20],
    person_data: {
      person_id: 73,
      name: "David Orzie /Steed/",
      birthday: "1904-12-06",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "74": {
    parent_of_family_id: [19],
    child_of_family_id: [21],
    person_data: {
      person_id: 74,
      name: "Eula /Steed/",
      birthday: "1905-04-08",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "75": {
    parent_of_family_id: [17],
    child_of_family_id: [],
    person_data: {
      person_id: 75,
      name: "James /Roberts/",
      birthday: "1854-03-09",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "76": {
    parent_of_family_id: [17],
    child_of_family_id: [],
    person_data: {
      person_id: 76,
      name: "Aldura Coleman /Smith/",
      birthday: "1858-01-14",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "77": {
    parent_of_family_id: [],
    child_of_family_id: [16],
    person_data: {
      person_id: 77,
      name: "Glen Charles /Roberts/",
      birthday: "1918-03-05",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "78": {
    parent_of_family_id: [],
    child_of_family_id: [16],
    person_data: {
      person_id: 78,
      name: "Ronald J /Roberts/",
      birthday: "1912-02-01",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "79": {
    parent_of_family_id: [],
    child_of_family_id: [16],
    person_data: {
      person_id: 79,
      name: "Lee Roy /Roberts/",
      birthday: "1922-06-14",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "80": {
    parent_of_family_id: [],
    child_of_family_id: [16],
    person_data: {
      person_id: 80,
      name: 'Maleen "Mick" /Roberts/',
      birthday: "1915-08-12",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "81": {
    parent_of_family_id: [18],
    child_of_family_id: [],
    person_data: {
      person_id: 81,
      name: "Johanes ( John) /Helquist/",
      birthday: "1861-01-11",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "82": {
    parent_of_family_id: [18],
    child_of_family_id: [],
    person_data: {
      person_id: 82,
      name: "Margaret Ann /Jones/",
      birthday: "1872-09-28",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "83": {
    parent_of_family_id: [],
    child_of_family_id: [17],
    person_data: {
      person_id: 83,
      name: "Alfred /Roberts/",
      birthday: "1888-03-27",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "84": {
    parent_of_family_id: [],
    child_of_family_id: [17],
    person_data: {
      person_id: 84,
      name: "Adelaide Ann /Roberts/",
      birthday: "1893-02-11",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "85": {
    parent_of_family_id: [],
    child_of_family_id: [17],
    person_data: {
      person_id: 85,
      name: "James Roy /Roberts/",
      birthday: "1882-11-06",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "86": {
    parent_of_family_id: [],
    child_of_family_id: [17],
    person_data: {
      person_id: 86,
      name: "Estella /Roberts/",
      birthday: "1885-02-25",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "87": {
    parent_of_family_id: [],
    child_of_family_id: [18],
    person_data: {
      person_id: 87,
      name: "Charles Oral /Helquist/",
      birthday: "1897-05-06",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "88": {
    parent_of_family_id: [],
    child_of_family_id: [18],
    person_data: {
      person_id: 88,
      name: "Perry /Helquist/",
      birthday: "1905-02-22",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "89": {
    parent_of_family_id: [],
    child_of_family_id: [18],
    person_data: {
      person_id: 89,
      name: "Margaritta /Helquist/",
      birthday: "1899-06-13",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "90": {
    parent_of_family_id: [],
    child_of_family_id: [18],
    person_data: {
      person_id: 90,
      name: "John Maurice /Helquist/",
      birthday: "1895-09-13",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "91": {
    parent_of_family_id: [],
    child_of_family_id: [18],
    person_data: {
      person_id: 91,
      name: "Verlillian /Helquist/",
      birthday: "1901-11-17",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "92": {
    parent_of_family_id: [],
    child_of_family_id: [18],
    person_data: {
      person_id: 92,
      name: "Thelma /Helquist/",
      birthday: "1907-04-05",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "93": {
    parent_of_family_id: [20],
    child_of_family_id: [],
    person_data: {
      person_id: 93,
      name: "David Moroni /Steed/",
      birthday: "1879-10-28",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "94": {
    parent_of_family_id: [20],
    child_of_family_id: [],
    person_data: {
      person_id: 94,
      name: "Annie Bettie /Anderson/",
      birthday: "1884-05-08",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "95": {
    parent_of_family_id: [],
    child_of_family_id: [19],
    person_data: {
      person_id: 95,
      name: "David Jay /Steed/",
      birthday: "1936-04-18",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "96": {
    parent_of_family_id: [],
    child_of_family_id: [19],
    person_data: {
      person_id: 96,
      name: "Douglas Wayne /Steed/",
      birthday: "1932-06-28",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "97": {
    parent_of_family_id: [21],
    child_of_family_id: [],
    person_data: {
      person_id: 97,
      name: "Nymphus Jay /Green/",
      birthday: "1881-12-04",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "98": {
    parent_of_family_id: [21],
    child_of_family_id: [],
    person_data: {
      person_id: 98,
      name: "Ida Jerusha /Smith/",
      birthday: "1887-10-05",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "99": {
    parent_of_family_id: [],
    child_of_family_id: [20],
    person_data: {
      person_id: 99,
      name: "Nona Grace /Steed/",
      birthday: "1912-03-03",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "100": {
    parent_of_family_id: [],
    child_of_family_id: [20],
    person_data: {
      person_id: 100,
      name: "Thelma /Smith/",
      birthday: "1909-03-18",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "101": {
    parent_of_family_id: [],
    child_of_family_id: [20],
    person_data: {
      person_id: 101,
      name: "/Steed/",
      birthday: "1914-09-28",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "102": {
    parent_of_family_id: [],
    child_of_family_id: [20],
    person_data: {
      person_id: 102,
      name: "Merlin John /Steed/",
      birthday: "1907-06-02",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "103": {
    parent_of_family_id: [],
    child_of_family_id: [20],
    person_data: {
      person_id: 103,
      name: "Donald Anderson /Steed/",
      birthday: "1919-11-12",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "104": {
    parent_of_family_id: [],
    child_of_family_id: [20],
    person_data: {
      person_id: 104,
      name: "Glen Lyle /Steed/",
      birthday: "1927-03-30",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "105": {
    parent_of_family_id: [],
    child_of_family_id: [20],
    person_data: {
      person_id: 105,
      name: "Bertram /Steed/",
      birthday: "1914-09-28",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "106": {
    parent_of_family_id: [],
    child_of_family_id: [20],
    person_data: {
      person_id: 106,
      name: "Annie Beth /Steed/",
      birthday: "1923-05-01",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "107": {
    parent_of_family_id: [],
    child_of_family_id: [20],
    person_data: {
      person_id: 107,
      name: "Delbert Lyman /Steed/",
      birthday: "1916-12-04",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "108": {
    parent_of_family_id: [],
    child_of_family_id: [21],
    person_data: {
      person_id: 108,
      name: "Adeline Smith /Greene/",
      birthday: "1907-02-01",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "109": {
    parent_of_family_id: [],
    child_of_family_id: [21],
    person_data: {
      person_id: 109,
      name: "Harold /Greene/",
      birthday: "1908-01-01",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "110": {
    parent_of_family_id: [],
    child_of_family_id: [21],
    person_data: {
      person_id: 110,
      name: "Phyllis Greene /Spencer/",
      birthday: "1910-02-11",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "111": {
    parent_of_family_id: [],
    child_of_family_id: [21],
    person_data: {
      person_id: 111,
      name: "Jay Lyle /Green/",
      birthday: "1912-01-11",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "112": {
    parent_of_family_id: [],
    child_of_family_id: [21],
    person_data: {
      person_id: 112,
      name: "Ida Elizabeth /Green/",
      birthday: "1914-09-15",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "113": {
    parent_of_family_id: [],
    child_of_family_id: [21],
    person_data: {
      person_id: 113,
      name: "James Merril /Greene/",
      birthday: "1917-11-19",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "114": {
    parent_of_family_id: [],
    child_of_family_id: [21],
    person_data: {
      person_id: 114,
      name: "Jesse Darrel /Greene/",
      birthday: "1917-11-19",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
  "115": {
    parent_of_family_id: [],
    child_of_family_id: [21],
    person_data: {
      person_id: 115,
      name: "Eugene Alva /Greene/",
      birthday: "1921-04-30",
      photo: null,
      date_of_death: null,
      sex: "male" as Sex,
      is_alive: true,
    },
  },
};
